# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Hyperspectral(object):

    def setupUi(self, Hyperspectral):
        Hyperspectral.setObjectName("Hyperspectral")
        Hyperspectral.resize(678, 485)
        Hyperspectral.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(Hyperspectral)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 0, 2, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 5, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_2.addWidget(self.graphicsView_2, 3, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.tab_2)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 3, 3, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setMinimumSize(QtCore.QSize(100, 100))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMaximumSize(QtCore.QSize(200, 26))
        self.pushButton_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_4.setAcceptDrops(False)
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_4.setAutoRepeatInterval(100)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 13, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_2, 0, 8, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 2, 13, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 7, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_3.addWidget(self.comboBox_3, 2, 8, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 16, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 2, 15, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 17, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 14, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 16, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 2, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 10, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 10, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setMaximumSize(QtCore.QSize(83, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 15, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 7, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget_2, 4, 1, 1, 3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        Hyperspectral.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Hyperspectral)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Hyperspectral.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Hyperspectral)
        self.statusbar.setObjectName("statusbar")
        Hyperspectral.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(Hyperspectral)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(Hyperspectral)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtWidgets.QAction(Hyperspectral)
        self.action_4.setObjectName("action_4")
        self.menuFile.addAction(self.action)
        self.menuFile.addAction(self.action_2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_4)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Hyperspectral)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton.clicked.connect(Hyperspectral.OnClickedTab1Button)
        self.comboBox.currentIndexChanged['QString'].connect(Hyperspectral.ShowBond)
        self.pushButton_4.clicked.connect(Hyperspectral.OnCilickedTab2Butto1)
        self.pushButton_3.clicked.connect(Hyperspectral.OnCilickedTab2Butto2)
        self.pushButton_2.clicked.connect(Hyperspectral.OnCilickedTab2Butto3)
        self.pushButton_5.clicked.connect(Hyperspectral.OnCilickedTab2Butto4)
        self.listWidget.currentRowChanged['int'].connect(Hyperspectral.OnChangedTab2listWidget)
        self.comboBox_2.currentIndexChanged['QString'].connect(Hyperspectral.OnChangedTab2ComboBox1)
        QtCore.QMetaObject.connectSlotsByName(Hyperspectral)

    def retranslateUi(self, Hyperspectral):
        _translate = QtCore.QCoreApplication.translate
        Hyperspectral.setWindowTitle(_translate("Hyperspectral", "MainWindow"))
        self.pushButton.setText(_translate("Hyperspectral", "读取文件"))
        self.label_3.setText(_translate("Hyperspectral", "Samples:"))
        self.label_2.setText(_translate("Hyperspectral", "Lines:"))
        self.label.setText(_translate("Hyperspectral", "<html><head/><body><p>文件名称:</p></body></html>"))
        self.label_4.setText(_translate("Hyperspectral", "Bands:"))
        self.label_5.setText(_translate("Hyperspectral", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">当前波段</span></p></body></html>"))
        self.label_6.setText(_translate("Hyperspectral", "波段范围:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Hyperspectral", "高光谱数据预览"))
        self.pushButton_4.setText(_translate("Hyperspectral", "选择文件夹"))
        self.pushButton_3.setText(_translate("Hyperspectral", "手动选择区域"))
        self.label_8.setText(_translate("Hyperspectral", "波段选择"))
        self.label_12.setText(_translate("Hyperspectral", "最小半径"))
        self.pushButton_5.setText(_translate("Hyperspectral", "手动生成数据"))
        self.pushButton_2.setText(_translate("Hyperspectral", "一键生成数据"))
        self.label_14.setText(_translate("Hyperspectral", "形状选择"))
        self.label_13.setText(_translate("Hyperspectral", "最大半径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Hyperspectral", "数据提取"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Hyperspectral", "判別模型构建"))
        self.menuFile.setTitle(_translate("Hyperspectral", "菜单"))
        self.action.setText(_translate("Hyperspectral", "读取高光谱数据文件"))
        self.action_2.setText(_translate("Hyperspectral", "从文件夹中读取"))
        self.action_4.setText(_translate("Hyperspectral", "关于本软件"))

