# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Hyperspectral(object):
    def setupUi(self, Hyperspectral):
        Hyperspectral.setObjectName("Hyperspectral")
        Hyperspectral.resize(668, 486)
        Hyperspectral.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(Hyperspectral)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 0, 2, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 5, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.tab_2)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 3, 3, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setMinimumSize(QtCore.QSize(100, 100))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 9, 9)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMaximumSize(QtCore.QSize(200, 26))
        self.pushButton_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_4.setAcceptDrops(False)
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_4.setAutoRepeatInterval(100)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 13, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_2, 0, 8, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 2, 13, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 7, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_3.addWidget(self.comboBox_3, 2, 8, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 16, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 17, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 14, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 16, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 2, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 10, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 10, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 7, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setMaximumSize(QtCore.QSize(83, 16777215))
        self.pushButton_2.setAutoRepeatInterval(100)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 15, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 2, 15, 1, 1)
        self.gridLayout_2.addWidget(self.widget_2, 4, 1, 1, 3)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_2.addWidget(self.graphicsView_2, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.listWidget_3 = QtWidgets.QListWidget(self.tab_3)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_5.addWidget(self.listWidget_3, 0, 0, 15, 1)
        self.listWidget_4 = QtWidgets.QListWidget(self.tab_3)
        self.listWidget_4.setObjectName("listWidget_4")
        self.gridLayout_5.addWidget(self.listWidget_4, 0, 1, 15, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 0, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_5.addWidget(self.pushButton_15, 1, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_5.addWidget(self.pushButton_10, 2, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_5.addWidget(self.pushButton_11, 3, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem7, 4, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 5, 2, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_5.addWidget(self.comboBox_6, 6, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_5.addWidget(self.pushButton_16, 7, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem8, 8, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 9, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_5.addWidget(self.comboBox_5, 10, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 11, 2, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_5.addWidget(self.comboBox_4, 12, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_5.addWidget(self.pushButton_14, 13, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 14, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 9)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEdit = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_4.addWidget(self.textEdit, 0, 6, 1, 8)
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_4.addWidget(self.pushButton_17, 4, 12, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 4, 10, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_4.addWidget(self.lineEdit_4, 4, 11, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_4.addWidget(self.lineEdit_5, 2, 11, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 2, 10, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_4.addWidget(self.lineEdit_6, 2, 8, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 4, 8, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 4, 7, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 2, 13, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 2, 5, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 2, 6, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 2, 3, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 2, 9, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_4.addWidget(self.pushButton_7, 4, 4, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_5)
        self.listWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_2.setDragEnabled(False)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_4.addWidget(self.listWidget_2, 0, 3, 1, 3)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 2, 4, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_18.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_4.addWidget(self.pushButton_18, 2, 12, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 2, 7, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 4, 3, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        Hyperspectral.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Hyperspectral)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Hyperspectral.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Hyperspectral)
        self.statusbar.setObjectName("statusbar")
        Hyperspectral.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(Hyperspectral)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(Hyperspectral)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtWidgets.QAction(Hyperspectral)
        self.action_4.setObjectName("action_4")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_4)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Hyperspectral)
        self.tabWidget.setCurrentIndex(2)
        self.pushButton.clicked.connect(Hyperspectral.OnClickedTab1Button)
        self.listWidget.currentRowChanged['int'].connect(Hyperspectral.OnChangedTab2listWidget)
        self.comboBox.currentIndexChanged['QString'].connect(Hyperspectral.ShowBond)
        self.pushButton_4.clicked.connect(Hyperspectral.OnCilickedTab2Butto1)
        self.comboBox_2.currentIndexChanged['QString'].connect(Hyperspectral.OnChangedTab2ComboBox1)
        self.pushButton_3.clicked.connect(Hyperspectral.OnCilickedTab2Butto2)
        self.pushButton_2.clicked.connect(Hyperspectral.OnCilickedTab2Butto3)
        self.pushButton_5.clicked.connect(Hyperspectral.OnCilickedTab2Butto4)
        self.pushButton_6.clicked.connect(Hyperspectral.ReadDirTab4)
        self.pushButton_7.clicked.connect(Hyperspectral.ClearListTab4)
        self.pushButton_18.clicked.connect(Hyperspectral.ShowResultsTab4)
        self.pushButton_17.clicked.connect(Hyperspectral.MatrixTab4)
        self.pushButton_11.clicked.connect(Hyperspectral.ReadMatTab2)
        self.pushButton_16.clicked.connect(Hyperspectral.MovingFliter)
        self.pushButton_14.clicked.connect(Hyperspectral.SGFliter)
        QtCore.QMetaObject.connectSlotsByName(Hyperspectral)
        Hyperspectral.setTabOrder(self.lineEdit, self.lineEdit_2)
        Hyperspectral.setTabOrder(self.lineEdit_2, self.comboBox_2)
        Hyperspectral.setTabOrder(self.comboBox_2, self.comboBox_3)
        Hyperspectral.setTabOrder(self.comboBox_3, self.pushButton_4)
        Hyperspectral.setTabOrder(self.pushButton_4, self.pushButton_3)
        Hyperspectral.setTabOrder(self.pushButton_3, self.listWidget)
        Hyperspectral.setTabOrder(self.listWidget, self.graphicsView_2)
        Hyperspectral.setTabOrder(self.graphicsView_2, self.comboBox)
        Hyperspectral.setTabOrder(self.comboBox, self.graphicsView)
        Hyperspectral.setTabOrder(self.graphicsView, self.pushButton)

    def retranslateUi(self, Hyperspectral):
        _translate = QtCore.QCoreApplication.translate
        Hyperspectral.setWindowTitle(_translate("Hyperspectral", "高光谱数据分析软件"))
        self.pushButton.setText(_translate("Hyperspectral", "读取文件"))
        self.label_3.setText(_translate("Hyperspectral", "Samples:"))
        self.label_2.setText(_translate("Hyperspectral", "Lines:"))
        self.label.setText(_translate("Hyperspectral", "<html><head/><body><p>文件名称:</p></body></html>"))
        self.label_4.setText(_translate("Hyperspectral", "Bands:"))
        self.label_5.setText(_translate("Hyperspectral", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">当前波段</span></p></body></html>"))
        self.label_6.setText(_translate("Hyperspectral", "波段范围:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Hyperspectral", "高光谱数据预览"))
        self.pushButton_4.setText(_translate("Hyperspectral", "选择文件夹"))
        self.pushButton_3.setText(_translate("Hyperspectral", "手动选择区域"))
        self.label_8.setText(_translate("Hyperspectral", "波段选择"))
        self.label_12.setText(_translate("Hyperspectral", "最小半径"))
        self.label_14.setText(_translate("Hyperspectral", "形状选择"))
        self.label_13.setText(_translate("Hyperspectral", "最大半径"))
        self.pushButton_2.setText(_translate("Hyperspectral", "一键生成数据"))
        self.pushButton_5.setText(_translate("Hyperspectral", "手动生成数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Hyperspectral", "数据提取"))
        self.pushButton_15.setText(_translate("Hyperspectral", "读取Excel"))
        self.pushButton_10.setText(_translate("Hyperspectral", "读取CSV"))
        self.pushButton_11.setText(_translate("Hyperspectral", "读取Mat"))
        self.label_21.setText(_translate("Hyperspectral", "窗口大小"))
        self.pushButton_16.setText(_translate("Hyperspectral", "Moing平滑"))
        self.label_19.setText(_translate("Hyperspectral", "窗口大小"))
        self.label_20.setText(_translate("Hyperspectral", "多项式幂数"))
        self.pushButton_14.setText(_translate("Hyperspectral", "SG平滑"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Hyperspectral", "数据平滑"))
        self.textEdit.setHtml(_translate("Hyperspectral", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_17.setText(_translate("Hyperspectral", "生成混淆矩阵"))
        self.label_15.setText(_translate("Hyperspectral", "KFold"))
        self.label_18.setText(_translate("Hyperspectral", "子空间维度"))
        self.label_16.setText(_translate("Hyperspectral", "迭代次数"))
        self.pushButton_7.setText(_translate("Hyperspectral", "清空列表"))
        self.pushButton_6.setText(_translate("Hyperspectral", "读取数据文件夹"))
        self.pushButton_18.setText(_translate("Hyperspectral", "分类"))
        self.label_17.setText(_translate("Hyperspectral", "弱分类器个数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Hyperspectral", "判別模型构建"))
        self.menuFile.setTitle(_translate("Hyperspectral", "菜单"))
        self.action.setText(_translate("Hyperspectral", "读取高光谱数据文件"))
        self.action_2.setText(_translate("Hyperspectral", "从文件夹中读取"))
        self.action_4.setText(_translate("Hyperspectral", "关于本软件"))

